### PR TITLE
Fix indexing of C# projects.

### PR DESCRIPTION
**Pull request by ericholscher**

### CODE REVIEW

**Comment by ericholscher** [comment]
I was just getting errors on building docs, and this fixes it. It came from your refactor a bit ago, so I don't quite know what is going on :)

**Comment by agjohnson** [comment]
So this was a piece that I didn't touch besides incrementing the index of `x` to target the second element in the tuple from the domain data dict, which is now `(obj_type, obj_name) -> (doc_name,)`. The domain dict was `obj_name -> (doc_name, obj_type)` before, so the original lambda would have been returning the lower case first letter of the dict key? So the lambda now returns the lower case first letter of `obj_name` from the dict key tuple? Unless I'm missing something. Seems like a strange thing that Sphinx would throw an error on either way.

Less magic would be good here though, if we both had to guess at this.

**Comment by ericholscher** [comment]
Agreed. Lots o' magic. This is currently breaking my local build, so I'm :+1: on merging it, then finding a proper solution.

**Comment by agjohnson** [comment]
+1, can address #23 later

**Pull request merged**
