### PR TITLE
Deprecate project

### PR DESCRIPTION
**Pull request by astrojuanlu**
Hello everyone, we would like to communicate that we are effectively deprecating sphinxcontrib-dotnetdomain. Unfortunately, we haven't been maintaining the package for a long time, and it is now incompatible with newer versions of Sphinx (3.x and 4.x, see https://github.com/readthedocs/sphinxcontrib-dotnetdomain/pull/68).

I am leaving this pull request open for a few days in case folks want to chime in and express their views, and in principle, we will merge it and archive the repository before the Christmas holidays.

### CODE REVIEW

**Comment by cx-leonelsanches** [comment]
Hi, @astrojuanlu. I opened a PR with some fixes. Can that be approved?

Otherwise I'll have to fork the project to another name and continue it.

**Comment by astrojuanlu** [comment]
Hi @cx-leonelsanches , thank you for your contribution. From our side, we'd rather prefer that you fork the project. If you end up uploading it to PyPI, we can advertise the fork from our README before archiving it.

**Comment by cx-leonelsanches** [comment]
@astrojuanlu Sounds good to me. Can you folks please give me access to the package in PyPI? My username is cx-leonelsanches.

**Comment by astrojuanlu** [comment]
@cx-leonelsanches sorry I didn't explain myself correctly: we'd prefer that you fork the project and pick a different name for the PyPI package. We are not considering giving PyPI access to external folks at this point.

**Comment by cx-leonelsanches** [comment]
@astrojuanlu Okay, that's fine. I can do that.

**Pull request merged**
